import Foundation

enum PhraseBank {
    static let dailyPhrases: [String] = [
        "Sunscreen check-in: become a human SPF, not a melted marshmallow.",
        "Beat the rays, not just the snooze button.",
        "Your skin loves you more than your excuses.",
        "UV called — it says, 'I see your bottle, not your face.':)",
        "Sunscreen is cheaper than a tan line clinic visit.",
        "Cloudy day? Still sunscreen, still hero. No cape required.",
        "Put it on, set a new glow standard.",
        "You are one scan away from SPF enlightenment.",
        "Shade starts with you, but we want your shoulders too.",
        "Bottled protection: detected. Hero mode: unlocked.",
        "Your bottle has spoken. You have listened?",
        "Scan up, SPF up.",
        "You don’t have to chase the perfect tan, just protect the skin.",
        "Selfie with sunscreen: because sunscreen selfies are the new profile checks.",
        "No SPF? No peace.",
        "Rays are working. So are you.",
        "Your future self just sent a thank-you memo.",
        "Burnout starts with sunscreen burnout.",
        "Apply, confirm, conquer the day.",
        "Bottle in frame, worries tamed.",
        "SPF on, stress off.",
        "Keep cool, stay cool, and keep reapplying smart.",
        "Your skin is making a comeback with this one.",
        "UV can’t outsmart a consistent checker.",
        "You didn’t skip leg day; don’t skip sunscreen.",
        "One tap, one scan, one better skin day.",
        "If your skin had a bank account, sunscreen is a deposit.",
        "Today’s sunscreen status: legendary in progress.",
        "Not a filter, actual protection.",
        "Apply now, glow later.",
        "Scan the label, save your shade.",
        "The only line you need today is an SPF line.",
        "Sunscreen before drama.",
        "Your bottle and your habits are both on camera today.",
        "No tan, just confidence.",
        "The sun is powerful; your routine is stronger.",
        "If SPF is a habit, this is your attendance.",
        "Put it on like you mean it.",
        "Sunscreen streak: sun-safe and smug.",
        "Today's forecast: protected.",
        "Even indoors, your skin appreciates consistency.",
        "Scan. Smile. Stay safe.",
        "You survived another sunny day. Verified."
    ]

    static let weeklyPhrases: [String] = [
        "Report: you treated your face like an asset, and your body like a brand-new umbrella. You’re 1% better at avoiding sun-sorry.",
        "Report: 7-day sunshine audit complete — your skin has sent a standing ovation for consistency.",
        "Report: your streak is doing pushups; keep doing reps and your skin will thank you later.",
        "Report: you missed a few waves, but the sunscreen still has your back for this week.",
        "Report: applied like a champ! Only the sun needed a reminder, not your routine.",
        "Report: you got a little inconsistent, but still way cooler than that one coworker using instant coffee SPF.",
        "Report: seven days, some yes's, some nope's — your sunscreen story still has a plot twist.",
        "Report: your skin report card says 'mostly responsible, occasional napper under shade.'",
        "Report: a solid sunscreen week wrapped; your epidermis just sent a peace letter.",
        "Report: UV called and said, 'nice moves, I can’t catch you this week.'",
        "Report: your bottles got scanned, selfies validated, and drama minimized.",
        "Report: you kept the SPF meter mostly green; the red zone got a temporary visit.",
        "Report: sunscreen discipline: powered by routines and occasional panic at 5:58 PM.",
        "Report: your streak is sun-safe enough to be used as a life motto.",
        "Report: if this were a movie, today you would be the anti-sunburn montage.",
        "Report: your protective habits are now officially more reliable than your first coffee.",
        "Report: congratulations, your skin is doing its own little vacation.",
        "Report: mission summary: bottle found, rays delayed, confidence raised.",
        "Report: weekly win unlocked: protected. Bonus points for the selfie check-ins.",
        "Report: your missed days are now known; your future sunscreen moves are clear and funny."
    ]
}
