#!/usr/bin/env bash
#
# Populate local App Store review environment variables for manual submission.
# Values are written to .state/appstore/review.env, which is ignored by git.
#
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "$0")/../.." && pwd)"
# shellcheck source=/dev/null
source "$ROOT_DIR/scripts/tooling/common.sh"
source_appstore_review_env

OUTPUT_PATH="$ROOT_DIR/.state/appstore/review.env"

prompt_required() {
  local variable="$1"
  local prompt="$2"
  local current="${!variable:-}"
  local value
  local suffix=""

  if [ -n "$current" ]; then
    suffix=" [press Enter to keep existing]"
  fi
  printf '%s%s: ' "$prompt" "$suffix"
  IFS= read -r value
  if [ -z "$value" ]; then
    value="$current"
  fi
  if [ -z "$value" ]; then
    printf '%s is required.\n' "$variable" >&2
    exit 2
  fi
  printf -v "$variable" '%s' "$value"
}

prompt_yes_no_gate() {
  local variable="$1"
  local prompt="$2"
  local current="${!variable:-0}"
  local default="n"
  local value

  if [ "$current" = "1" ]; then
    default="y"
  fi
  printf '%s [%s]: ' "$prompt" "$default"
  IFS= read -r value
  value="${value:-$default}"
  case "$value" in
  y | Y | yes | YES)
    printf -v "$variable" '1'
    ;;
  n | N | no | NO)
    printf -v "$variable" '0'
    ;;
  *)
    printf 'Answer y or n.\n' >&2
    exit 2
    ;;
  esac
}

prompt_required ASC_KEY_ID "App Store Connect key ID"
prompt_required ASC_ISSUER_ID "App Store Connect issuer ID"
prompt_required ASC_KEY_FILE "Path to App Store Connect API private key file"
if [ ! -f "$ASC_KEY_FILE" ]; then
  printf 'ASC_KEY_FILE does not exist: %s\n' "$ASC_KEY_FILE" >&2
  exit 2
fi

prompt_required SUNCLUB_APP_REVIEW_CONTACT_FIRST_NAME "App Review contact first name"
prompt_required SUNCLUB_APP_REVIEW_CONTACT_LAST_NAME "App Review contact last name"
prompt_required SUNCLUB_APP_REVIEW_CONTACT_EMAIL "App Review contact email"
prompt_required SUNCLUB_APP_REVIEW_CONTACT_PHONE "App Review contact phone"

prompt_yes_no_gate \
  SUNCLUB_APP_PRIVACY_COMPLETED \
  "Have you completed App Privacy in App Store Connect with data-not-collected answers"

printf 'Type NOT_MEDICAL_DEVICE after setting regulated medical device status in App Store Connect: '
IFS= read -r medical_status
medical_status="${medical_status:-${SUNCLUB_REGULATED_MEDICAL_DEVICE_STATUS:-}}"
if [ "$medical_status" != "NOT_MEDICAL_DEVICE" ]; then
  printf 'SUNCLUB_REGULATED_MEDICAL_DEVICE_STATUS must be NOT_MEDICAL_DEVICE.\n' >&2
  exit 2
fi
SUNCLUB_REGULATED_MEDICAL_DEVICE_STATUS="$medical_status"

mkdir -p "$(dirname -- "$OUTPUT_PATH")"
umask 077
temp_file="$(mktemp "$OUTPUT_PATH.tmp.XXXXXX")"
{
  printf '# Sunclub App Store review submission environment.\n'
  printf '# Generated by scripts/appstore/review-env.sh. Do not commit this file.\n'
  printf 'export ASC_KEY_ID=%q\n' "$ASC_KEY_ID"
  printf 'export ASC_ISSUER_ID=%q\n' "$ASC_ISSUER_ID"
  printf 'export ASC_KEY_FILE=%q\n' "$ASC_KEY_FILE"
  printf 'export SUNCLUB_APP_REVIEW_CONTACT_FIRST_NAME=%q\n' "$SUNCLUB_APP_REVIEW_CONTACT_FIRST_NAME"
  printf 'export SUNCLUB_APP_REVIEW_CONTACT_LAST_NAME=%q\n' "$SUNCLUB_APP_REVIEW_CONTACT_LAST_NAME"
  printf 'export SUNCLUB_APP_REVIEW_CONTACT_EMAIL=%q\n' "$SUNCLUB_APP_REVIEW_CONTACT_EMAIL"
  printf 'export SUNCLUB_APP_REVIEW_CONTACT_PHONE=%q\n' "$SUNCLUB_APP_REVIEW_CONTACT_PHONE"
  printf 'export SUNCLUB_APP_PRIVACY_COMPLETED=%q\n' "$SUNCLUB_APP_PRIVACY_COMPLETED"
  printf 'export SUNCLUB_REGULATED_MEDICAL_DEVICE_STATUS=%q\n' "$SUNCLUB_REGULATED_MEDICAL_DEVICE_STATUS"
} >"$temp_file"
chmod 600 "$temp_file"
mv "$temp_file" "$OUTPUT_PATH"
chmod 600 "$OUTPUT_PATH"

printf 'Wrote %s with mode 600.\n' "$OUTPUT_PATH"
