import Foundation

enum PhraseBank {
    static let dailyPhrases: [String] = [
        "Sunclub check-in: bottle ready, routine ready.",
        "Start today protected and keep the streak moving.",
        "Find your bottle, log your check-in, get on with the day.",
        "Good routines start early. Sunscreen counts.",
        "One quick check-in now makes the rest of the day easier.",
        "Your bottle is the easy win. Take it.",
        "Keep the habit simple: apply, check in, move.",
        "Today's sunscreen goes on before the day speeds up.",
        "Stay consistent now so future you doesn't have to catch up.",
        "Bottle in hand. Check-in in reach.",
        "The best sunscreen is the one you actually use. Start there.",
        "Lock in today's protection and keep the routine alive.",
        "Club rule: protect first, then head out.",
        "Start with sunscreen. The rest can follow.",
        "A quick check-in beats a skipped day.",
        "Your streak likes mornings. So does sunscreen.",
        "Keep your skin covered and your routine clean.",
        "Make today's bottle count before the sun does.",
        "Check in now. Thank yourself later.",
        "Consistency looks good on you.",
        "Bottle found. Day started right.",
        "Keep the routine steady even when the weather isn't.",
        "One scan or one selfie and today's done.",
        "Build the habit one protected day at a time.",
        "Good skin days start with boring consistency. That's the point.",
        "Today's bottle is part of the plan.",
        "Small step, strong routine.",
        "If the bottle is nearby, today's already easier.",
        "Stay stocked, stay ready, stay protected.",
        "Get today's check-in done before the calendar notices.",
        "The routine works when you show up for it.",
        "Sunscreen first. Everything else after.",
        "Keep the streak moving with one quick check-in.",
        "The right sunscreen is the one you reach for every day.",
        "Stay ahead of the rays, not behind on the habit.",
        "Your next bottle is easier to plan when the routine is real.",
        "Build the habit now so reorders are obvious later.",
        "Daily check-ins make good sunscreen easier to keep.",
        "Keep your bottle in rotation.",
        "Today's protection starts with one small step.",
        "Sunclub check-in: stay ready for this bottle and the next.",
        "Strong routine, low drama, one bottle at a time.",
        "Every check-in makes the habit easier to keep."
    ]

    static let weeklyPhrases: [String] = [
        "Club note: strong routines are built on ordinary days like these.",
        "Club note: keep the bottle that works close and the next bottle closer.",
        "Club note: the more repeatable the routine, the easier the right sunscreen becomes.",
        "Club note: missed days happen; what matters is getting back into rhythm.",
        "Club note: consistency is still the fastest way to better skin decisions.",
        "Club note: keep one bottle in use and one in sight.",
        "Club note: a simple routine beats a perfect plan every time.",
        "Club note: the goal is not more effort, just fewer skipped days.",
        "Club note: when the routine is real, reordering gets easier.",
        "Club note: keep building the habit until sunscreen feels automatic.",
        "Club note: the right bottle is the one that keeps showing up with you.",
        "Club note: steady weeks make it easier to notice when you're running low.",
        "Club note: protect early, restock early, repeat.",
        "Club note: a good streak starts with today's check-in, not last week's.",
        "Club note: keep your sunscreen in the same place and the routine follows.",
        "Club note: fewer decisions, more consistency.",
        "Club note: the habit is working when sunscreen feels like part of leaving the house.",
        "Club note: the routine gets lighter once it becomes normal.",
        "Club note: keep this bottle moving and line up the next one before you need it.",
        "Club note: routine first, product second, but both matter."
    ]
}
